version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install boto3 botocore

  build:
    commands:
      - echo "=== Starting Python Error Fixes ==="
      - |
        for file in $(find . -type f -name "*.py" ! -name "fix_python_errors.py"); do
          echo "\nChecking file: $file"
          echo "------------------------"
          
          # Save original content
          cp "$file" "$file.backup"
          
          # Try to fix the file
          if python3 fix_python_errors.py "$file"; then
            # Show changes if any were made
            if ! cmp -s "$file" "$file.backup"; then
              echo "Changes made to $file:"
              diff "$file.backup" "$file"
            else
              echo "No changes needed in $file"
            fi
          else
            echo "Error while processing $file"
          fi
          
          # Clean up backup
          rm "$file.backup"
        done
      - echo "=== Python Error Fixes Complete ==="

artifacts:
  files:
    - "**/*.py"
  exclude-paths:
    - "**/__pycache__/**"
    - "**/venv/**"